title: ＶＡＰＯＲＷＡＶＥ ＭＡＬＬ
description: Gallery of dreams.
baseurl: /
url: https://vaporwavemall.com
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
include: ['_pages']